In [1]:
import numpy as np

In [5]:
print(np.array([1,2,3,4]))

[1 2 3 4]


In [6]:
print(np.arange(1,10,2))

[1 3 5 7 9]


In [8]:
l = range(1000)
%timeit [i**2 for i in l]

981 µs ± 210 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
a = np.arange(1000)
%timeit a**2

4.37 µs ± 450 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Creating Arrays

In [10]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
a.ndim  # 1 dimensional array

1

In [13]:
a.shape

(4,)

In [19]:
b = a.reshape(4,1)
print(b)

[[1]
 [2]
 [3]
 [4]]


In [18]:
b.ndim  # 2 dimensional array


2

In [20]:
len(b)

4

In [21]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [25]:
c.reshape(3,2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
c.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
# 3 dimensional array

d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,5,9]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 5 9]]]


In [31]:
d.ndim

3

In [38]:
d[1:,1:]  # 2nd dimension 2 row

array([[[1, 5, 9]]])

In [44]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [45]:
np.ones(3)

array([1., 1., 1.])

In [46]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [48]:
np.zeros([1,2])

array([[0., 0.]])

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
a = np.eye(4,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [58]:
a = np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [64]:
print(np.random.rand(2,5))  # uniform variate 0 to 1

[[0.2390224  0.82498571 0.23007256 0.02671251 0.57503103]
 [0.30806843 0.6217414  0.03858029 0.85826123 0.30824703]]


In [65]:
print(np.random.randn(2,5)) # normal standard variate mean = 0 and std = 1

[[-0.39463328  0.71834493 -1.84625685  0.69057649 -1.87766875]
 [ 1.1007665   0.76584839 -0.46324968 -0.94431822  1.6543484 ]]


In [67]:
print(np.random.randint(2,50,5))

[31 17 34 46 22]


In [68]:
a = np.arange(10)
a[5:7]

array([5, 6])

In [71]:
a = np.diag([1,2,3])
a[1,1]

2

In [72]:
a[2,1] = 5

In [73]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

## Slicing

In [90]:
b = np.arange(0,20,2)
b  = b[b<11]
b

array([ 0,  2,  4,  6,  8, 10])

In [91]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [93]:
a[4:] = b[::-1] 
a

array([ 0,  1,  2,  3, 10,  8,  6,  4,  2,  0])

## Copy and view

In [145]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [140]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [141]:
np.shares_memory(a,b)

True

In [142]:
b[0] = 10

In [143]:
b

array([10,  2,  4,  6,  8])

In [144]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

above when i change b[0] variable a itself changed

In [147]:
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [148]:
c[0]=10
c

array([10,  2,  4,  6,  8])

In [149]:
# here variable a wont change since i used copy()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
np.shares_memory(a,c)

False

## Masking

In [161]:
a = np.random.randint(0,20,15)
a

array([ 7,  8, 15, 12, 13,  9,  0,  9,  6, 13, 15,  3,  9,  1, 15])

In [162]:
mask = (a%2==0)
b

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False,  True, False,  True, False,  True])

In [163]:
extract_from_a = a[mask]
extract_from_a

array([ 8, 12,  0,  6])

In [164]:
a[mask] = -1

In [165]:
a

array([ 7, -1, 15, -1, 13,  9, -1,  9, -1, 13, 15,  3,  9,  1, 15])

In [166]:
# Indexing with an array of integers

a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [167]:
a[[2,3,3,2,4]]

array([20, 30, 30, 20, 40])

In [168]:
a[[9,7]] = 100

In [169]:
a

array([  0,  10,  20,  30,  40,  50,  60, 100,  80, 100])