# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [35]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat)) # inverse matrix

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.78809289 0.87579924 0.67586237 0.58043873 0.37315926]
 [0.11495398 0.92812107 0.179463   0.53503292 0.5548553 ]
 [0.8411191  0.19365611 0.21811979 0.53354788 0.64405659]
 [0.38166248 0.85474716 0.47129516 0.92783501 0.03005559]
 [0.45346504 0.43183663 0.36883151 0.58952815 0.99136088]]

[[ 0.79652568  0.43967293  1.5549618  -0.47370131  0.63688937]
 [-0.46110144 -1.25278956  1.7677119   0.06974586 -0.05589221]
 [ 1.13044458  1.82070514  0.07539993 -0.86521152  2.17319262]
 [ 0.67541238  0.76039766 -0.65277875 -1.65238475  0.1471629 ]
 [-0.21691626 -1.01671555 -0.0096981   0.3469085   1.63743204]
 [-0.39384975  2.09891871  0.20735811  0.35038326 -0.67131414]
 [ 0.89671295  0.58221083 -0.10799678 -0.37664887 -0.31844909]
 [-0.81845801  0.27314245  0.78633245 -0.80271108  1.40498658]
 [ 0.31501252  0.07589159  1.50805403  0.07480414  1.14260662]
 [ 1.00399579 -0.77729278  0.5819678   2.00190275  1.35851105]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5414758348354104
0.9240074186528859


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.030055593581483353
2.1731926207596697


## Numpy accessing entries

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.95156208 -0.19380318  0.68579091 -0.86937515  0.12531037  0.30353976
 -0.97880043  0.00318651 -0.69648464  0.24268563 -0.19788778 -0.08629108
  0.94043094  0.01470823  0.01824188  0.10630987 -0.51404781  0.61096494
 -2.43962245]
-0.9788004311251758


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.12531037  0.30353976 -0.97880043  0.00318651 -0.69648464]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.95156208 -0.86937515 -0.97880043  0.24268563  0.94043094]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.78809289 0.87579924 0.67586237 0.58043873 0.37315926]
 [0.11495398 0.92812107 0.179463   0.53503292 0.5548553 ]
 [0.8411191  0.19365611 0.21811979 0.53354788 0.64405659]
 [0.38166248 0.85474716 0.47129516 0.92783501 0.03005559]
 [0.45346504 0.43183663 0.36883151 0.58952815 0.99136088]]
0.179463000416606
0.179463000416606


In [19]:
print(rand_mat[0:2,1:3])

[[0.87579924 0.67586237]
 [0.92812107 0.179463  ]]


In [21]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.95156208 -0.19380318  0.68579091  1.          2.          0.30353976
 -0.97880043  0.00318651 -0.69648464  0.24268563 -0.19788778 -0.08629108
  0.94043094  0.01470823  0.01824188  0.10630987 -0.51404781  0.61096494
 -2.43962245]

[ 9.51562077e-01 -1.93803180e-01  6.85790907e-01  4.00000000e+00
  4.00000000e+00  3.03539758e-01 -9.78800431e-01  3.18651236e-03
 -6.96484640e-01  2.42685627e-01 -1.97887777e-01 -8.62910815e-02
  9.40430937e-01  1.47082322e-02  1.82418841e-02  1.06309874e-01
 -5.14047813e-01  6.10964938e-01 -2.43962245e+00]

[ 0.95156208 -0.19380318  0.68579091  1.          2.          0.30353976
 -0.97880043  0.00318651 -0.69648464  0.24268563 -0.19788778 -0.08629108
  0.94043094  0.01470823  0.01824188  0.10630987 -0.51404781  0.61096494
 -2.43962245]


In [22]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.78809289 0.87579924 0.67586237 0.58043873 0.37315926]
 [0.11495398 0.92812107 0.179463   0.53503292 0.5548553 ]
 [0.8411191  0.19365611 0.21811979 0.53354788 0.64405659]
 [0.38166248 0.85474716 0.47129516 0.92783501 0.03005559]
 [0.45346504 0.43183663 0.36883151 0.58952815 0.99136088]]

[[0.78809289 0.87579924 0.67586237 0.58043873 0.37315926]
 [0.11495398 0.92812107 0.179463   0.         0.        ]
 [0.8411191  0.19365611 0.21811979 0.         0.        ]
 [0.38166248 0.85474716 0.47129516 0.92783501 0.03005559]
 [0.45346504 0.43183663 0.36883151 0.58952815 0.99136088]]


In [23]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.78809289 0.87579924 0.67586237]
 [0.11495398 0.92812107 0.179463  ]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [24]:
print(rand_mat)

[[3.         3.         3.         0.58043873 0.37315926]
 [3.         3.         3.         0.         0.        ]
 [0.8411191  0.19365611 0.21811979 0.         0.        ]
 [0.38166248 0.85474716 0.47129516 0.92783501 0.03005559]
 [0.45346504 0.43183663 0.36883151 0.58952815 0.99136088]]


In [25]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.58043873 0.37315926]
 [3.         3.         3.         0.         0.        ]
 [0.8411191  0.19365611 0.21811979 0.         0.        ]
 [0.38166248 0.85474716 0.47129516 0.92783501 0.03005559]
 [0.45346504 0.43183663 0.36883151 0.58952815 0.99136088]]


## Saving and Loading Numpy Arrays

In [27]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.39952705  0.57665281 -0.24165538  0.12475233  0.52237072 -1.30194844
  0.89077737 -0.20730277 -0.61021974 -0.05834864  0.26956994 -0.6730342
 -0.52419516  0.55228724  1.11543446]
[False  True False  True  True False  True False False False  True False
 False  True  True]
[0.57665281 0.12475233 0.52237072 0.89077737 0.26956994 0.55228724
 1.11543446]


In [28]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.79652568  0.43967293  1.5549618  -0.47370131  0.63688937]
 [-0.46110144 -1.25278956  1.7677119   0.06974586 -0.05589221]
 [ 1.13044458  1.82070514  0.07539993 -0.86521152  2.17319262]
 [ 0.67541238  0.76039766 -0.65277875 -1.65238475  0.1471629 ]
 [-0.21691626 -1.01671555 -0.0096981   0.3469085   1.63743204]
 [-0.39384975  2.09891871  0.20735811  0.35038326 -0.67131414]
 [ 0.89671295  0.58221083 -0.10799678 -0.37664887 -0.31844909]
 [-0.81845801  0.27314245  0.78633245 -0.80271108  1.40498658]
 [ 0.31501252  0.07589159  1.50805403  0.07480414  1.14260662]
 [ 1.00399579 -0.77729278  0.5819678   2.00190275  1.35851105]]
[0.79652568 0.43967293 1.5549618  0.63688937 1.7677119  0.06974586
 1.13044458 1.82070514 0.07539993 2.17319262 0.67541238 0.76039766
 0.1471629  0.3469085  1.63743204 2.09891871 0.20735811 0.35038326
 0.89671295 0.58221083 0.27314245 0.78633245 1.40498658 0.31501252
 0.07589159 1.50805403 0.07480414 1.14260662 1.00399579 0.5819678
 2.00190275 1.35851105]


In [29]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.39952705  0.57665281 -0.24165538  0.12475233  0.52237072 -1.30194844
  0.89077737 -0.20730277 -0.61021974 -0.05834864  0.26956994 -0.6730342
 -0.52419516  0.55228724  1.11543446]

[-0.39952705 -5.         -0.24165538  0.12475233 -5.         -1.30194844
 -5.         -0.20730277 -0.61021974 -0.05834864  0.26956994 -0.6730342
 -0.52419516 -5.         -5.        ]


In [30]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [31]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [32]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 0.79652568  0.43967293  1.5549618  -0.47370131  0.63688937]
 [-0.46110144 -1.25278956  1.7677119   0.06974586 -0.05589221]
 [ 1.13044458  1.82070514  0.07539993 -0.86521152  2.17319262]
 [ 0.67541238  0.76039766 -0.65277875 -1.65238475  0.1471629 ]
 [-0.21691626 -1.01671555 -0.0096981   0.3469085   1.63743204]
 [-0.39384975  2.09891871  0.20735811  0.35038326 -0.67131414]
 [ 0.89671295  0.58221083 -0.10799678 -0.37664887 -0.31844909]
 [-0.81845801  0.27314245  0.78633245 -0.80271108  1.40498658]
 [ 0.31501252  0.07589159  1.50805403  0.07480414  1.14260662]
 [ 1.00399579 -0.77729278  0.5819678   2.00190275  1.35851105]]



In [33]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.58043873 0.37315926]
 [3.         3.         3.         0.         0.        ]
 [0.8411191  0.19365611 0.21811979 0.         0.        ]
 [0.38166248 0.85474716 0.47129516 0.92783501 0.03005559]
 [0.45346504 0.43183663 0.36883151 0.58952815 0.99136088]]

[[ 0.79652568  0.43967293  1.5549618  -0.47370131  0.63688937]
 [-0.46110144 -1.25278956  1.7677119   0.06974586 -0.05589221]
 [ 1.13044458  1.82070514  0.07539993 -0.86521152  2.17319262]
 [ 0.67541238  0.76039766 -0.65277875 -1.65238475  0.1471629 ]
 [-0.21691626 -1.01671555 -0.0096981   0.3469085   1.63743204]
 [-0.39384975  2.09891871  0.20735811  0.35038326 -0.67131414]
 [ 0.89671295  0.58221083 -0.10799678 -0.37664887 -0.31844909]
 [-0.81845801  0.27314245  0.78633245 -0.80271108  1.40498658]
 [ 0.31501252  0.07589159  1.50805403  0.07480414  1.14260662]
 [ 1.00399579 -0.77729278  0.5819678   2.00190275  1.35851105]]
[[3.         3.         3.         0.58043873 0.37315926]
 [3.         3.    

In [34]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.58043873 0.37315926]
 [3.         3.         3.         0.         0.        ]
 [0.8411191  0.19365611 0.21811979 0.         0.        ]
 [0.38166248 0.85474716 0.47129516 0.92783501 0.03005559]
 [0.45346504 0.43183663 0.36883151 0.58952815 0.99136088]]

[[3.         3.         3.         0.58043873 0.37315926]
 [3.         3.         3.         0.         0.        ]
 [0.8411191  0.19365611 0.21811979 0.         0.        ]
 [0.38166248 0.85474716 0.47129516 0.92783501 0.03005559]
 [0.45346504 0.43183663 0.36883151 0.58952815 0.99136088]]
