In [1]:
import numpy as np
import pandas as pd

In [11]:
df = pd.DataFrame(np.arange(0,20).reshape(4,5), index = ['row1','row2','row3','row4'], columns=['col1','col2','col3','col4','col5'])

In [12]:
df

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [18]:
df.loc['row1': 'row3']

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14

In [20]:
df.iloc[:3]

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14

In [22]:
df.iloc[1:3,3:]

col4  col5
row2     8     9
row3    13    14

In [24]:
df.loc['row1']

col1    0
col2    1
col3    2
col4    3
col5    4
Name: row1, dtype: int32

In [31]:
df.loc['row1'].values

array([0, 1, 2, 3, 4])

In [33]:
df.values

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [146]:
df.iloc[2:3]

col1  col2  col3  col4  col5
row3    10    11    12    13    14

In [44]:
df.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5'], dtype='object')

In [47]:
df['col1'].value_counts()

15    1
5     1
10    1
0     1
Name: col1, dtype: int64

In [50]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
col5    0
dtype: int64

In [55]:
df['col1'].unique()

array([ 0,  5, 10, 15], dtype=int64)

In [59]:
df[['col1','col2']]

col1  col2
row1     0     1
row2     5     6
row3    10    11
row4    15    16

In [66]:
df.loc[['row1','row2']]

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9

In [67]:
mylist = [5.4,6.1,1.7,99.8]
myarray = np.array(mylist)
print(myarray)

[ 5.4  6.1  1.7 99.8]


In [74]:
pd.Series(myarray,index=['row1','row2','row3','row4'])

row1     5.4
row2     6.1
row3     1.7
row4    99.8
dtype: float64

In [298]:
data = pd.read_csv('Downloads/mtcars.csv')

In [107]:
data.head()

name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [115]:
data['name'].value_counts

<bound method IndexOpsMixin.value_counts of 0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: name, dtype: object>

In [116]:
data.shape

(32, 12)

In [120]:
data.size

384

In [133]:
data.iloc[[1,2]]

name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
1  Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2     Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   

   carb  
1     4  
2     1

In [140]:
data[['name','cyl']].head()

name  cyl
0          Mazda RX4    6
1      Mazda RX4 Wag    6
2         Datsun 710    4
3     Hornet 4 Drive    6
4  Hornet Sportabout    8

In [153]:
data[data['cyl'] < 5]

name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
2       Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
7        Merc 240D  24.4    4  146.7   62  3.69  3.190  20.00   1   0     4   
8         Merc 230  22.8    4  140.8   95  3.92  3.150  22.90   1   0     4   
17        Fiat 128  32.4    4   78.7   66  4.08  2.200  19.47   1   1     4   
18     Honda Civic  30.4    4   75.7   52  4.93  1.615  18.52   1   1     4   
19  Toyota Corolla  33.9    4   71.1   65  4.22  1.835  19.90   1   1     4   
20   Toyota Corona  21.5    4  120.1   97  3.70  2.465  20.01   1   0     3   
25       Fiat X1-9  27.3    4   79.0   66  4.08  1.935  18.90   1   1     4   
26   Porsche 914-2  26.0    4  120.3   91  4.43  2.140  16.70   0   1     5   
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.90   1   1     5   
31      Volvo 142E  21.4    4  121.0  109  4.11  2.780  18.60   1   1     4   

    carb  
2      1  
7      2  
8      2  
17     1  
18     2  
19     1  
20     1  
25     1  
26     2  
27     2  
31     2

In [154]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
name    32 non-null object
mpg     32 non-null float64
cyl     32 non-null int64
disp    32 non-null float64
hp      32 non-null int64
drat    32 non-null float64
wt      32 non-null float64
qsec    32 non-null float64
vs      32 non-null int64
am      32 non-null int64
gear    32 non-null int64
carb    32 non-null int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB


In [156]:
data.columns

Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')

In [ ]:
#data.describe

In [167]:
data[data['name'] == 'Toyota Corona'] 

name   mpg  cyl   disp  hp  drat     wt   qsec  vs  am  gear  \
20  Toyota Corona  21.5    4  120.1  97   3.7  2.465  20.01   1   0     3   

    carb  
20     1

In [169]:
data['cyl'].value_counts()

8    14
4    11
6     7
Name: cyl, dtype: int64

In [170]:
data.iloc[2:5]

name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
2     1  
3     1  
4     2

In [171]:
data.corr()

mpg       cyl      disp        hp      drat        wt      qsec  \
mpg   1.000000 -0.852162 -0.847551 -0.776168  0.681172 -0.867659  0.418684   
cyl  -0.852162  1.000000  0.902033  0.832447 -0.699938  0.782496 -0.591242   
disp -0.847551  0.902033  1.000000  0.790949 -0.710214  0.887980 -0.433698   
hp   -0.776168  0.832447  0.790949  1.000000 -0.448759  0.658748 -0.708223   
drat  0.681172 -0.699938 -0.710214 -0.448759  1.000000 -0.712441  0.091205   
wt   -0.867659  0.782496  0.887980  0.658748 -0.712441  1.000000 -0.174716   
qsec  0.418684 -0.591242 -0.433698 -0.708223  0.091205 -0.174716  1.000000   
vs    0.664039 -0.810812 -0.710416 -0.723097  0.440278 -0.554916  0.744535   
am    0.599832 -0.522607 -0.591227 -0.243204  0.712711 -0.692495 -0.229861   
gear  0.480285 -0.492687 -0.555569 -0.125704  0.699610 -0.583287 -0.212682   
carb -0.550925  0.526988  0.394977  0.749812 -0.090790  0.427606 -0.656249   

            vs        am      gear      carb  
mpg   0.664039  0.599832  0.480285 -0.550925  
cyl  -0.810812 -0.522607 -0.492687  0.526988  
disp -0.710416 -0.591227 -0.555569  0.394977  
hp   -0.723097 -0.243204 -0.125704  0.749812  
drat  0.440278  0.712711  0.699610 -0.090790  
wt   -0.554916 -0.692495 -0.583287  0.427606  
qsec  0.744535 -0.229861 -0.212682 -0.656249  
vs    1.000000  0.168345  0.206023 -0.569607  
am    0.168345  1.000000  0.794059  0.057534  
gear  0.206023  0.794059  1.000000  0.274073  
carb -0.569607  0.057534  0.274073  1.000000

In [174]:
data.head()

name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [185]:
data.iloc[1:5,[3,5,6]]

disp  drat     wt
1  160.0  3.90  2.875
2  108.0  3.85  2.320
3  258.0  3.08  3.215
4  360.0  3.15  3.440

In [186]:
data.loc[1:6,['cyl','hp','am']]

cyl   hp  am
1    6  110   1
2    4   93   1
3    6  110   0
4    8  175   0
5    6  105   0
6    8  245   0

In [196]:
numeric_data = data._get_numeric_data()
numeric_data.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [204]:
numeric_data.head() > 0

mpg   cyl  disp    hp  drat    wt  qsec     vs     am  gear  carb
0  True  True  True  True  True  True  True  False   True  True  True
1  True  True  True  True  True  True  True  False   True  True  True
2  True  True  True  True  True  True  True   True   True  True  True
3  True  True  True  True  True  True  True   True  False  True  True
4  True  True  True  True  True  True  True  False  False  True  True

In [206]:
numeric_data[numeric_data < 10].head()

mpg  cyl  disp  hp  drat     wt  qsec  vs  am  gear  carb
0  NaN    6   NaN NaN  3.90  2.620   NaN   0   1     4     4
1  NaN    6   NaN NaN  3.90  2.875   NaN   0   1     4     4
2  NaN    4   NaN NaN  3.85  2.320   NaN   1   1     4     1
3  NaN    6   NaN NaN  3.08  3.215   NaN   1   0     3     1
4  NaN    8   NaN NaN  3.15  3.440   NaN   0   0     3     2

In [202]:
pd.isnull(data).sum()

name    0
mpg     0
cyl     0
disp    0
hp      0
drat    0
wt      0
qsec    0
vs      0
am      0
gear    0
carb    0
dtype: int64

In [222]:
numeric_data.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [226]:
numeric_data.drop('vs',axis=1).head()  # it will drop the column


mpg  cyl   disp   hp  drat     wt   qsec  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0     3     2

In [227]:
numeric_data.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [229]:
numeric_data.loc[0]

mpg      21.00
cyl       6.00
disp    160.00
hp      110.00
drat      3.90
wt        2.62
qsec     16.46
vs        0.00
am        1.00
gear      4.00
carb      4.00
Name: 0, dtype: float64

In [230]:
numeric_data.drop([0,1],axis=0).head() # delete the rows

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2
5  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3     1
6  14.3    8  360.0  245  3.21  3.570  15.84   0   0     3     4

In [233]:
# remove dataset index labels

numeric_data.reset_index().head()


index   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0      0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2      2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3      3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4      4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [235]:
numeric_data.head()   # index doesn't included for dataset

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [236]:
numeric_data.reset_index(inplace=True)

In [238]:
numeric_data.head()

index   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0      0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2      2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3      3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4      4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [240]:
numeric_data.reset_index(inplace= False).head()

level_0  index   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0        0      0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1        1      1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2        2      2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3        3      3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4        4      4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [243]:
numeric_data.head()

index   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0      0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1      1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2      2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3      3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4      4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [252]:
# numeric_data.drop('index',axis=1,inplace = True)
numeric_data.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [265]:
numeric_data.head(2)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4

In [ ]:
# join 
# data.join(dfata2,how='right') # outer, inner, left, and right work the same as merge

In [267]:
new_data = numeric_data[(numeric_data['hp'] == 110) & (numeric_data['vs'] == 0)]
print(new_data)

    mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0  21.0    6  160.0  110   3.9  2.620  16.46   0   1     4     4
1  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4     4


In [268]:
def square(s):
    return s ** 2

In [270]:
new_data['carb'].apply(square)

0    16
1    16
Name: carb, dtype: int64

In [275]:
data.head(1)

name   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
0  Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4

In [278]:
data['name'].apply(len).head()

0     9
1    13
2    10
3    14
4    17
Name: name, dtype: int64

In [281]:
df = new_data[['gear','carb']]

In [284]:
df.applymap(square)

gear  carb
0    16    16
1    16    16

In [287]:
data.head(1)

name   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  carb
0  Mazda RX4  21.0    6  160.0  110   3.9  2.62  16.46   0   1     4     4

In [300]:
del new_data['carb']

In [301]:
new_data

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear
0  21.0    6  160.0  110   3.9  2.620  16.46   0   1     4
1  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4

In [302]:
new_data.std

<bound method DataFrame.std of     mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear
0  21.0    6  160.0  110   3.9  2.620  16.46   0   1     4
1  21.0    6  160.0  110   3.9  2.875  17.02   0   1     4>